services:
  postgres:
    image: postgres:18
    container_name: java-study-postgres
    environment:
      POSTGRES_DB: java-study
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"